name: Application Deployment

on:
  push:
    branches: [main]

env:
  CONTAINER_PREFIX: isp-dashboard

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_REPO: ghcr.io/${{ github.actor }}/${{vars.APPLICATION_NAME}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Parse Environment Variables
        id: parse-env
        run: |
          cat <<EOF > .env
          ${{ secrets.ENV_VARIABLES }}
          EOF
          SERVICE_PORT=$(awk -F '=' '/^PORT=/ {print $2}' .env)
          echo "SERVICE_PORT=$SERVICE_PORT" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ env.DOCKER_REPO }}:latest .
          docker push ${{ env.DOCKER_REPO }}:latest

          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Generate Deployment Files
        run: |
          cat <<EOF > envs
          ${{ secrets.ENV_VARIABLES }}
          EOF
          cat <<EOF > docker-compose.yml
          services:
            ${CONTAINER_PREFIX}-proxy:
              image: nginx:alpine
              container_name: ${CONTAINER_PREFIX}-proxy
              ports:
                - "${SERVICE_PORT}:${SERVICE_PORT}"
              volumes:
                - ./nginx.conf:/etc/nginx/conf.d/default.conf
              networks:
                - app-net
              depends_on:
                - ${CONTAINER_PREFIX}-app
              restart: always

            ${CONTAINER_PREFIX}-app:
              image: ${{ env.DOCKER_REPO }}:latest
              container_name: ${CONTAINER_PREFIX}-app
              env_file: .env.local
              networks:
                - app-net
              restart: always
          networks:
            app-net:
              driver: bridge
          EOF

          cat <<EOF > nginx.conf
          server {
            listen ${SERVICE_PORT};
            location / {
              proxy_pass http://${CONTAINER_PREFIX}-app:${SERVICE_PORT};
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$scheme;
            }
          }
          EOF

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: |
            docker-compose.yml
            nginx.conf
            envs

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_REPO: ghcr.io/${{ github.actor }}/${{vars.APPLICATION_NAME}}
    strategy:
      matrix:
        host: ["isp.easypay.co.tz"]

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-files

      - name: Create remote directory if doesn't exist
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ matrix.host }}
          username: ${{ vars.SSH_USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: mkdir -p /var/www/${{env.CONTAINER_PREFIX}}-${{ vars.APPLICATION_NAME }}

      - name: Copy File to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ matrix.host }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.yml,nginx.conf,envs"
          target: "/var/www/${{env.CONTAINER_PREFIX}}-${{ vars.APPLICATION_NAME }}"

      - name: Deploy to ${{ matrix.host }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ matrix.host }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/${{env.CONTAINER_PREFIX}}-${{vars.APPLICATION_NAME}}

            mv envs .env.local

            # Set up container 
            docker login -u "${{ github.actor }}" -p "${{ secrets.GHCR_ACCESS_TOKEN }} ghcr.io"

            docker compose pull
            docker compose up -d --force-recreate

            # Cleanup temporary volumes, images and containers
            docker system prune -a --volumes -f